# MySQL linking
mysql_connection:
    host: '127.0.0.1'
    port: 3306
    user: 'root'
    password: 'Zhang123.'

mysql_database:
    database: 'amhs'
    table_names: ['ohtc_map','ohtc_position','transfer_table']
    
