# MySQL linking
mysql_connection:
    host: '127.0.0.1'
    port: 3306
    user: 'root'
    password: 'Zhang123.'

mysql_database:
    database: 'amhs'
    table_map_name: 'ohtc_map'
    table_position_name: 'ohtc_position'
    table_order_name: 'transfer_table'
